server:
  port: 8080
  servlet:
    session:
      timeout: 7200
  shutdown:
    grace-period: 7200
server.shutdown: graceful
# server.servlet.session.timeout: 3600 # 1시간 (단위: 초)
---
logging.level.root: info
logging.level.org.springframework.security: debug
---
security.basic.enabled: false
---
app:
  dispatch:
    commands:
    - opcode: test.command
      commandClassName: com.inzi.mes.be.framework.dispatch.DispatchTestCommand
---
app:
  workflow:
    tasks:
    - name: emailSendServiceTask
      topicName: emailSendTopic
      taskClassName: com.inzi.mes.be.example.EmailSendTask
---
app:
  kafka:
    use: true
    topics:
      - topicName: mes-topic-response
        countOfPartition: 1
        countOfReplica: 1
    consumers:
      - consumerName: reply-consumer
        consumerInfo: reply-consumer
        topicName: topic-response
        groupId: consumer-group
        partition: 0
        countOfConcurrency: 1
        listenerBeanName: kafka.topic.example.listener  
---
app:
  authorization:
    permits:
    # type: all, has-any-role, has-a-role, authenticated
    # if type is all and anyRequest is true, then anyRequest().permitAll()
    - type: authenticated
      anyRequest: false
      matchers:
      - method: GET
        pathname: /api/v1/**
      - method: POST
        pathname: /api/v1/**
    - type: all
      anyRequest: false
      matchers:
      - method: GET
        pathname: /swagger-ui.html
      - method: GET
        pathname: /swagger-ui/**
      - method: GET
        pathname: /api-docs/**
      - method: POST
        pathname: /auth/**
      - method: GET
        pathname: /test/**
      - method: POST
        pathname: /test/**		
    #  - method: GET
    #    pathname: /test/api/v1/material/find/all/as-stream
    #- type: has-any-role
    #  anyRequest: false
    #  matchers:
    #  - method: PUT
    #    pathname: /test/pathname1
    #  - method: DELETE
    #    pathname: /test/pathname2
    #  roles:
    #  - ADMIN
    #  - USER
    #- type: has-a-role
    #  anyRequest: false
    #  matchers:
    #  - method: GET
    #    pathname: /test/pathname1
    #  role: ADMIN      
    #- type: authenticated
    #  anyRequest: false
    #  matchers:
    #  - method: POST
    #    pathname: pathname1 
---
app:
  cors:
    allAllowOrigins: false
    allowedOrigins:
    - http://localhost:3007
    #allAllowOriginPatterns: true
    #allowedOriginPatterns:
    #- ALL
    # allowedOrigins or allowedOriginPatterns can not be written at the same time 
    allAllowHeaders: true
    allowedHeaders:
    - authorization
    - aaa
    allAllowMethods: true
    allowedMethods:
    - ALL
    allowedCredential: true 
    # corsConfigurationPattern: /auth/** or /**
    corsConfigurationPattern: /**
---
app:
  authentication:
    jwt:
      issuer: MES-FRAMEWORK
      secret: hahahahahahahahahahahahahahahaaaaabdbsdjfskdjflaskdjflaskdfjlaskdfjaskldfjaslkdfjas
      token-access-expiration-milli-seconds: 10000000
      token-refresh-expiration-milli-seconds: 1000000000
---
# To use camunda springboot rest client
# feign:
#   client:
#     config:
#       default:
#         url: "http://localhost:8088/engine-rest/"
      # processInstance:
      #   url: "http://your-process-engine-host/engine-rest/"
      # processDefinition:
      #   url: "http://your-process-engine-host/engine-rest/"
      # message:
      #   url: "http://your-process-engine-host/engine-rest/"
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/quartz-test
    username: root
    password: 1qazxsw2  
  redis:
    host: localhost
    #password:
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
---
# To use camunda
spring.main.allow-bean-definition-overriding: true
camunda:
  bpm:
    client:
      base-url: http://localhost:8099/engine-rest
      basic-auth:
        username: demo
        password: demo
      # lock-duration: 1000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
      # subscriptions:
      #   emailSendTopic: # topic name of the External Service Task
      #     variable-names: [] # our business logic doesn't require any variables, so don't fetch them
      #     process-definition-key: Sample_test_process # only filter for External Tasks with this process definition key
  autoDeploy:
    bpmnResources: 'classpath*:**/*.bpmn'
    dmnResources: 'classpath*:**/*.dmn'
    formResources: 'classpath*:**/*.form'
    enabled: false
    failStartupOnError: false 
---
# To use springdoc
springdoc:
  version: '@project.version@'
  api-docs.path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    disable-query-params-without-oauth2: true
    doc-expansion: none
  #path-to-match:
  #- /auth/**
  #- /api/**
---
# To use java management
management:
  server.port: 8980
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      group:
        liveness.include: livenessState
        readiness.include: readinessState,db
        liveness.show-details: always
        readiness.show-details: always
      probes.enabled: true
      show-details: always
    info.enabled: true
    shutdown.enabled: true
  health:
    db.enabled: true
    readinessstate.enabled: true
    livenessstate.enabled: true   
endpoints:
  shutdown:
    enabled: true
---
# To use spring boot admin client
#spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8090
#        instance.name: Common Service Application
#        instance.service.base-url: http://localhost:8080